### ISSUE TITLE
Moving colours to the board

### ISSUE THREAD

**Issue by quozl** [sugarlabs/mastermind-activity#4]
Also, running the activity unchanged using Python 3 yields this problem; moving colours to the board is too sensitive to mouse position, and sometimes does not work.

**Comment by Saumya-Mishra9129** [comment]
https://github.com/sugarlabs/mastermind-activity/blob/a55a629181881b64835a26d13a1dae8c9c9507a4/constants.py#L36 Thinking maybe this could raise above issue.

**Comment by quozl** [comment]
Thanks.

**Comment by kshitijdshah99** [comment]
@quozl as far I understand this issue I have to port all necessary files to Python 3, right?

**Comment by quozl** [comment]
That's one way to look at it, but it can be more complicated.  Best not to speculate, but get it working and then discover you changed files.  :grin:

**Comment by ghost** [comment]
This activity already seems to be ported to python 3?

**Comment by quozl** [comment]
Aha, my clone was based on https://github.com/cvgarciarea/mastermind-activity and this repository is distinct, as a consequence of https://github.com/sugarlabs/mastermind-activity/issues/6

I've edited the issue.

**Comment by ghost** [comment]
I am not facing this issue, if issue can be elaborated further because when I drag the colors to board its working normally and not too much sensitive also is working properly without miss.

**Comment by quozl** [comment]
Good, thanks for verifying that.
